"""empty message

Revision ID: f2996feb29d2
Revises: 0f4a79a0398c
Create Date: 2023-08-13 15:34:06.259861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2996feb29d2'
down_revision = '0f4a79a0398c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('films')
        batch_op.drop_column('residents')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('residents', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('films', sa.VARCHAR(length=250), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
